### PR TITLE
add both sites production and development

### PR DESCRIPTION
**Pull request by jpradocueva**
Update README file to reflect the two websites.

### CODE REVIEW

**Comment by trombik** [comment]
this should be reviewed only after the content for the prod is deployed because there is no content in the bucket now.

**Comment by trombik** [comment]
blocked by #11

**Comment by jpradocueva** [comment]
@trombik the first time that a website is deployed do I need to do it by hand? Do I need to upload the corresponding files in the S3 backet by hand?

**Comment by trombik** [comment]
#11 will do that for you.

**Comment by trombik** [comment]
blocked by #19

**Pull request closed without merging**
